export const GET_POSTS = 'GET/POSTS';
export const SET_CURRENT_DETAILS = 'SET_CURRENT_DETAILS';
export const SET_CURRENT_COMMENTS = 'SET_CURRENT_COMMENTS';
export const GET_COMMENTS = 'GET_COMMENTS';
